# Configuration file for model architecture `HARDPurG`
model_params:
    # Static graph structure learner
    sgsl_params:
        static: True
        node_emb_dim: 32
        n_series: 321
        debug: False
    # Graph structure post processor
    sgspp_params:
        act: relu
        k: 20
        symmetric: False   # Currently fixed to False
        norm: sym   # Support sym and asym
    dgspp_params:
        k: 10
    # Spatial-Temporal pattern extractor
    st_params:
        n_layers: 3
        n_series: 321
        t_window: 168
        tran_state_h_dim: 32
        rnn_h_dim: 32
        rnn_n_layers: 1
        rnn_dropout: 0
        gconv_type: hop_aware_rectify
        hop_aware_rectify_fn: glu
        gconv_depth: 2
        gconv_h_dim: 32
        common_dropout: 0.2
        n_tids: null
        tid_emb_dim: null
        diw_emb_dim: null
        bn: False
    # Output
    skip_out_dim: 32
    out_dim: 1

fit_params:
