# model/MegaCRN

# == Model Hyperparameters ==
model_params:
    _target_: modeling.sotas.MegaCRN.MegaCRN
    # Spatial/Temporal pattern extractor
    st_params:
        n_layers: 1
        n_series: 207
        h_dim: 64
        enc_in_dim: 1
        dec_in_dim: 2
        n_adjs: 2
        max_diffusion_step: 2
        use_curriculum_learning: True
        cl_decay_steps: 2000        
    mem_params:
        mem_num: 20
        mem_dim: 64
    loss_params:
        lamb: 0.01
        lamb1: 0.01
    out_dim: 1
    out_len: 12

fit_params: