# model/STNorm

# == Model Hyperparameters ==
model_params:
    _target_: modeling.sotas.STNorm.STNorm
    # Spatial/Temporal Convolution Module
    st_params:
        n_layers: 4
        tcn_in_dim: 32
        gcn_in_dim: 32
        kernel_size: 2
        dilation_factor: 2
        snorm: True
        tnorm: True
        bn: False
    in_dim: 2
    skip_dim: 32
    end_dim: 32
    out_len: 12
    n_series: 207

fit_params: