# model/STSGCN

# == Model Hyperparameters ==
model_params:
    _target_: modeling.sotas.STSGCN.STSGCN
    # Spatial/Temporal pattern extractor
    st_params:
        n_layers: 4
        h_dim: 64
        gcn_depth: 3
        n_series: 207
        act: "glu"
        temporal_emb_dim: 64
        spatial_emb_dim: 64
    in_dim: 1
    in_len: 12
    device: "cuda:0"
    out_len: 12

fit_params: